version: '3'
services:
  api:
    build: .
    environment:
      APP_MODE: "development"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./tests:/tests
    depends_on:
      - postgres
      - huey
      - file-server

  huey:
    build: .
    command: /bin/sh -c 'python manage.py run_huey'
    environment:
      APP_MODE: "development"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  file-server:
    image: halverneus/static-file-server:v1.8.1
    user: root
    environment:
      FOLDER: "/data"
      PORT: 80
    ports:
      - 80:8888
    volumes:
      - ./tests/data:/data:ro
