#!/usr/bin/env bash

python manage.py makemigrations
python manage.py migrate

cat <<EOF | python manage.py shell
from django.contrib.auth.models import User
User.objects.filter(username="admin").exists() or User.objects.create_superuser("admin", "admin@example.com", "admin")
EOF

python manage.py collectstatic --noinput
gunicorn proj.wsgi --bind=0.0.0.0
python manage.py runserver 0.0.0.0:8000